name: one_ai
description: "OneAI – One Click, One Solution."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


#--------------- PACKAGES ---------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.20.2
  rive: ^0.13.0
  share: ^2.0.4
  lottie: ^3.1.0
  motion: ^2.0.1
  animate_do: ^4.0.0
  collection: ^1.18.0
  flutter_svg: ^2.0.17
  dart_openai: ^5.1.0
  file_picker: ^8.3.1
  url_launcher: ^6.2.5
  image_picker: ^1.1.2
  liquid_swipe: ^3.1.0
  glowy_borders: ^1.0.2
  glassmorphism: ^3.0.0
  flutter_dotenv: ^5.1.0
  iconify_flutter: ^0.0.7
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0
  smooth_page_indicator: ^1.1.0
  google_generative_ai: ^0.4.3
  local_hero_transform: ^0.0.3
  flutter_swipe_action_cell: ^3.1.3
  flutter_local_notifications: ^18.0.1
  flutter_staggered_animations: ^1.1.1
  animated_bottom_navigation_bar: ^1.3.3
  provider: ^6.0.5
  in_app_purchase: ^3.2.1
  shimmer: ^3.0.0

  # scanner
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0

  wifi_iot: ^0.3.19+1

  # Local Storage
  sqflite: ^2.3.2

  # Icons
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.6
  path_provider: ^2.1.2

  path: any
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.2
  firebase_messaging: ^15.0.2
  firebase_analytics: ^11.1.0

  # Added for go_router
  go_router: ^13.0.0

  # Added for cached_network_image
  cached_network_image: ^3.3.1

  flutter_tawkto: ^0.0.4

#--------------- ./ PACKAGES END ---------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/app-logo.png"


flutter:

  uses-material-design: true

  #--------------- LOCAL ASSETS ---------------#
  assets:
    #- assets/icons/categories
    - assets/logos/
    - assets/animations/
    - .env
  #--------------- ./ LOCAL ASSETS END ---------------#


  #--------------- LOCAL FONTS ---------------#
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf

    - family: HindSiliguri
      fonts:
        - asset: assets/fonts/HindSiliguri-Regular.ttf
  #--------------- ./ LOCAL FONTS END ---------------#