// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2t_DYXW5aQb00eiUwtAtFQNr0jlylZqo',
    appId: '1:480769648249:web:7b155caf004f5eca87d6a8',
    messagingSenderId: '480769648249',
    projectId: 'scannify-3ddee',
    authDomain: 'scannify-3ddee.firebaseapp.com',
    databaseURL: 'https://scannify-3ddee-default-rtdb.firebaseio.com',
    storageBucket: 'scannify-3ddee.appspot.com',
    measurementId: 'G-91GD8GVGVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPYxs3shA7QsGR8Yv_a0zEUd3K3AskiB0',
    appId: '1:480769648249:android:c546361c59fe2e0e87d6a8',
    messagingSenderId: '480769648249',
    projectId: 'scannify-3ddee',
    databaseURL: 'https://scannify-3ddee-default-rtdb.firebaseio.com',
    storageBucket: 'scannify-3ddee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkYlppOzjjV19NP47G4TmhvK2kOUvWMTE',
    appId: '1:480769648249:ios:027489429f5dcc6f87d6a8',
    messagingSenderId: '480769648249',
    projectId: 'scannify-3ddee',
    databaseURL: 'https://scannify-3ddee-default-rtdb.firebaseio.com',
    storageBucket: 'scannify-3ddee.appspot.com',
    androidClientId: '480769648249-65k4qjg7rfn4h6rq9q6dh7fm2oq009at.apps.googleusercontent.com',
    iosClientId: '480769648249-p3qspva5jbppd4kl4f4a23hd0soc6ef3.apps.googleusercontent.com',
    iosBundleId: 'com.example.DashScan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkYlppOzjjV19NP47G4TmhvK2kOUvWMTE',
    appId: '1:480769648249:ios:027489429f5dcc6f87d6a8',
    messagingSenderId: '480769648249',
    projectId: 'scannify-3ddee',
    databaseURL: 'https://scannify-3ddee-default-rtdb.firebaseio.com',
    storageBucket: 'scannify-3ddee.appspot.com',
    androidClientId: '480769648249-65k4qjg7rfn4h6rq9q6dh7fm2oq009at.apps.googleusercontent.com',
    iosClientId: '480769648249-p3qspva5jbppd4kl4f4a23hd0soc6ef3.apps.googleusercontent.com',
    iosBundleId: 'com.example.DashScan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2t_DYXW5aQb00eiUwtAtFQNr0jlylZqo',
    appId: '1:480769648249:web:fa3e1197cbd65b9387d6a8',
    messagingSenderId: '480769648249',
    projectId: 'scannify-3ddee',
    authDomain: 'scannify-3ddee.firebaseapp.com',
    databaseURL: 'https://scannify-3ddee-default-rtdb.firebaseio.com',
    storageBucket: 'scannify-3ddee.appspot.com',
    measurementId: 'G-EHTZ83R83W',
  );
}
