-keep class * extends androidx.fragment.app.Fragment {}
-keep class * extends android.os.Parcelable {}
-keep class * extends java.io.Serializable {}
-keepattributes *Annotation*
-keep class com.google.** { *; }
-keep class androidx.** { *; }
-keep class com.google.android.gms.** { *; }
-keep class com.google.firebase.** { *; }
-keepattributes Signature
-keep class com.android.billingclient.** { *; }
